version: '3.2'

volumes:
  prometheusstack_prometheus_data:
    external: true
  prometheusstack_grafana_data:
    external: true

networks:
  monitoring:

services:
  prometheus:
    image: prom/prometheus
    networks:
      - monitoring
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheusstack_prometheus_data:/prometheus
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
      - '-storage.local.path=/prometheus'
      - '-alertmanager.url=http://internal.ip:9093'
      - '-web.console.libraries=/usr/share/prometheus/console_libraries'
      - '-web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    links:
      - alertmanager:alertmanager
    restart: always
  node-exporter:
    image: prom/node-exporter
    volumes:
      - type: bind
        source: /proc
        target: /host/proc
      - type: bind
        source: /sys
        target: /host/sys
      - type: bind
        source: /
        target: /rootfs
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    ports:
      - 9100:9100
    networks:
      - monitoring
    restart: always
  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    networks:
      - monitoring
    restart: always
    command:
      - '-config.file=/etc/alertmanager/config.yml'
      - '-storage.path=/alertmanager'
  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=SUPERSECRET
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_ROOT_URL=http://monitor.server.com:3000
    volumes:
      - prometheusstack_grafana_data:/var/lib/grafana
    networks:
      - monitoring
